enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@preact/signals-react-transform@*":
    dependencies:
      "@babel/core": "*"
  electron-vite@*:
    dependencies:
      electron: "*"
      vite: "*"

yarnPath: .yarn/releases/yarn-4.2.1.cjs
