nodeLinker: node-modules
enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.1.1.cjs

packageExtensions: {
  'electron-vite@*': {
    dependencies: {
      'vite': '*',
      'electron': '*'
    }
  },
  '@preact/signals-react-transform@*': {
    dependencies: {
      '@babel/core': '*'
    }
  }
}