enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@preact/signals-react-transform@*":
    dependencies:
      "@babel/core": "*"
  electron-vite@*:
    dependencies:
      electron: "*"
      vite: "*"
  native-fetch@*:
    dependencies:
      undici: "*"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
