enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  electron-vite@*:
    dependencies:
      electron: "*"
      vite: "*"
  native-fetch@*:
    dependencies:
      undici: "*"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
